"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&uc)5d#w=*yxeozb71_1ghek+4wb3$w$hd)b7-(r24gs7m^@jf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', 'cling-blinks-idealize.ngrok-free.dev']
CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.dev']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'cloudinary_storage',
    'cloudinary',
    'users',
    'tours',
    'bookings',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Thêm cấu hình cho file tĩnh
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

FRONTEND_URL = 'http://localhost:5173'  # production: 'https://tourgo.vn'

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'TourBooking',
        'USER': 'sa',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '',  # Thường để trống cho bản Express hoặc đổi theo cấu hình thực tế
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;Encrypt=no',
        },
    }
}

# Nếu có biến môi trường DATABASE_URL (tức là chạy trên Render), nó sẽ dùng PostgreSQL của mây
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(default=os.environ.get('DATABASE_URL'), conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
CORS_ALLOW_ALL_ORIGINS = True # Mở cửa cho mọi link Frontend đều kết nối được (Rất cần thiết khi Deploy)
AUTH_USER_MODEL = 'users.User'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5172",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "http://localhost:5176",
    "http://127.0.0.1:5172",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
    "http://127.0.0.1:5176",
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}




from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(seconds=15),
#     'REFRESH_TOKEN_LIFETIME': timedelta(seconds=20),
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --- Configuration for Cloudinary (Khang) ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dgltxvqx2',
    'API_KEY': '368242959374932',
    'API_SECRET': 'JJHGEi4OyA-9w7TxMt70lu_Oz78'
}
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --- Configuration for Logging (Tân) ---
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'debug.log'),
            'formatter': 'verbose',
            # 🌟 CHỐT CHẶN 1: Ép ghi file bằng mã UTF-8 để không bị crash tiếng Việt trên Windows
            'encoding': 'utf-8', 
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            # Lưu ý: Mặc định StreamHandler trên terminal Windows đôi khi cũng cần utf-8 ở một số phiên bản Python cũ,
            # nhưng đặt encoding trực tiếp ở FileHandler phía trên là đã giải quyết được 99% lỗi crash của bạn rồi.
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'app_logger': {
            # 🌟 CHỐT CHẶN 2: Thêm 'console' để khi test ở Backend, Tân và Khánh 
            # có thể nhìn thấy dòng log "đăng nhập thành công" hiện ngay trên terminal luôn.
            'handlers': ['file', 'console'], 
            'level': 'INFO',
            'propagate': True,
        },
        'tours.email_service': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
# --- Email Settings for Gmail ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'nguyenvuhaaa123@gmail.com'
# EMAIL_HOST_PASSWORD = 'xmek qfzc aimn pvak'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# Trong backend/core/settings.py, tạm thời thay dòng này:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Thay vì smtp
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tankhang1410@gmail.com'
EMAIL_HOST_PASSWORD = 'rzoiobsgmsnokwbf'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_CREDENTIALS = True




# --- VietQR Settings (Khang) ---
VIETQR_BANK_ID = "MB" # Ví dụ: MB, VCB, ICB, ...
VIETQR_ACCOUNT_NO = "0376706825" 
VIETQR_ACCOUNT_NAME = "NGUYEN HUYNH NHAT TAN"

